services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - db
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
